# This workflow is triggered when someone create a new release in GitHub
# and checks the "This is a pre-relase" box.
name: Trigger Release creation

on:
  release:
    types: [prereleased]

jobs:
  on-release:
    runs-on: ubuntu-latest
    name: Compile
    steps:
      - uses: actions/checkout@v4
        with:
          ref: pax-web-7.3.29-jahia
      - name: Set environment variables from parameters
        shell: bash
        run: |
          echo "NEXUS_USERNAME=${{ secrets.NEXUS_USERNAME }}" >> $GITHUB_ENV
          echo "NEXUS_PASSWORD=${{ secrets.NEXUS_PASSWORD }}" >> $GITHUB_ENV
      # Setting up the SSH agent to be able to commit back to the repository
      # https://github.com/webfactory/ssh-agent
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.GH_SSH_PRIVATE_KEY_JAHIACI }}

      - name: Delete github tag ${{ github.event.release.tag_name }}
        shell: bash
        run: |
          git config user.email 'jahia-ci@jahia.com'
          git config user.name 'Jahia CI'
          git fetch --all
          git tag --delete ${{ github.event.release.tag_name }}
          git push origin :refs/tags/${{ github.event.release.tag_name }}

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Release with Maven
        run: |
          if [[ ${{ github.event.release.tag_name }} == web* ]] ;
          then
            TAG_VERSION=$(echo "${{ github.event.release.tag_name }}") # e.g. web-7.3.29-jahia2
            FINAL_RELEASE_VERSION=$(echo "$TAG_VERSION" | tr '_' '.' | cut -d'-' -f2-3)
            REVISION=$(echo $FINAL_RELEASE_VERSION | tr -d 'jahia' | cut -d'-' -f2)
            NEXT_REVISION=$(expr $REVISION + 1)
            NEXT_DEVELOPMENT_VERSION="$(echo $FINAL_RELEASE_VERSION | cut -d'-' -f1)-jahia${NEXT_REVISION}"-SNAPSHOT # e.g. 7.3.29-jahia3-SNAPSHOT
            mvn -B -s .github/maven.settings.xml -DdryRun=false -Dcheckstyle.skip=true -DskipLocalStaging=true -Dfindbugs.skip=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -Dtag=$TAG_VERSION -DreleaseVersion=$FINAL_RELEASE_VERSION -DdevelopmentVersion="$NEXT_DEVELOPMENT_VERSION" -DscmCommentPrefix="[skip ci] [maven-release-plugin]" -Darguments="-Dcheckstyle.skip=true -DskipLocalStaging=true -Dfindbugs.skip=true -Dmaven.javadoc.skip=true -Dgpg.skip=true" release:prepare
            mvn -B -s .github/maven.settings.xml -DdryRun=false -Dcheckstyle.skip=true -DskipLocalStaging=true -Dfindbugs.skip=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -Darguments="-Dcheckstyle.skip=true -DskipLocalStaging=true -Dfindbugs.skip=true -Dmaven.javadoc.skip=true -Dgpg.skip=true" release:perform
          else
            exit 1;
          fi
